
all:

clean:
	rm -f polybori.addition.html
	rm -f polybori.cluster.html
	rm -f polybori.cnf.html
	rm -f polybori.context.html
	rm -f polybori.easy_polynomials.html
	rm -f polybori.fglm.html
	rm -f polybori.intersect.html
	rm -f polybori.intpolys.html
	rm -f polybori.parallel.html
	rm -f polybori.parsegat.html
	rm -f polybori.plot.html
	rm -f polybori.rank.html

