
all:

clean:
	rm -f tutorial.4ct
	rm -f tutorial.4tc
	rm -f tutorial.aux
	rm -f tutorial.css
	rm -f tutorial.dvi
	rm -f tutorial.html
	rm -f tutorial.idv
	rm -f tutorial.lg
	rm -f tutorialli1.html
	rm -f tutorial.log
	rm -f tutorialse1.html
	rm -f tutorialse2.html
	rm -f tutorialse3.html
	rm -f tutorialse4.html
	rm -f tutorial.tmp
	rm -f tutorial.xref

